# Generated by Django 4.1.6 on 2023-02-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='create_activation_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
