# Generated by Django 4.1.6 on 2023-02-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_activation_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='create_activation_code',
            new_name='activation_code',
        ),
    ]
